# Module Three Activity

You will complete your assignment code in this **Module_Three_Activity.ipynb** Notebook file from the filetree that is pre-templated for your modification in accordance with the assignment instructions.

Once your code is complete, you will download this notebook as an HTML file by clicking **File**, then **Download As**, then **HTML (.html)** from the Jupyter menu bar. You will also need to download the csv output file of your merged data. Validate that your code and outputs are rendered in the html file before submission.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Missing Blocks:</i></b> Ensure that you have clicked <b><mark>Run</mark></b> for all blocks before downloading as an HTML file or the block may be missing from your submission.</span>
</div>

### Data Source Information
The sourcing information for the data sets can be found in the `README.md` file within the data folder.

To use this starter code file, replace the `data/sample_use_only/{data_name}.csv` with the reference to your selected data from the list below:

- `data/nyc_temperatures.csv`
- `data/nyc_weather_2018.csv`
- `data/parsed.csv`
- `data/quakes.db`
- `data/tsunamis.csv`
- `data/weather.db`
- `data/weather_by_station.csv`
- `data/weather_stations.csv`

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>To Begin:</i></b> replace each <b>data_file_#</b> entry sample data path with the path to your selected data sets.</span>
</div>

If you choose to only use two data files instead of three, comment out the reference to data_file_3.

In [17]:
data_file_1 = "data/sample_use_only/PopulationEstimates.csv"
data_file_2 = "data/sample_use_only/Education2023.csv"
# data_file_3 = "data/sample_use_only/Unemployment2023.csv"

## Installing Required Packages
If you have additional packages that you would like to use or install, add them to the **requirements.txt** file then run the next block.

In [18]:
%pip install --upgrade pip

Requirement already satisfied: pip in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (26.1.1)
Note: you may need to restart the kernel to use updated packages.

In [19]:
%pip install -r requirements.txt

Requirement already satisfied: ydata-profiling==4.16.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.10.0)
Requirement already satisfied: pydantic>=2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.13.3)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: htmlmin==0.1.12 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.33.1)
Requirement already satisfied: tqdm<5,>=4.48.2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.14.6)
Requirement already satisfied: typeguard<5,>=3 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.5.1)
Requirement already satisfied: imagehash==4.3.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.6)
Requirement already satisfied: dacite>=1.8 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.61.0)
Requirement already satisfied: PyWavelets in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: pillow in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (12.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from phik<0.13,>=0.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2026.4.22)
Requirement already satisfied: patsy>=0.5.6 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: typing_extensions>=4.14.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from typeguard<5,>=3->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: attrs>=19.3.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.4.2)
Requirement already satisfied: puremagic in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.30)
Requirement already satisfied: annotated-types>=0.6.0 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: six>=1.5 in /home/dukeph0/anaconda3/envs/ai_titan/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Import the Required Packages
If you have additional packages that you would like to import, add them here.

In [20]:
import pandas as pd
import numpy as np

## Loading and Preprocessing the Data
After you have selected your data set that wish to wrangle, replace the reference file path in the code block at the top of this Notebook, then run the following blocks.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you need to preprocess or clean your dataset before merging.</span>
</div>

### Data File 1 dataframe
Here we will load the data_file_1 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [21]:
data1 = pd.read_csv(data_file_1)

# Drop duplicate rows to ensure data integrity before any transformations.
data1.drop_duplicates(inplace=True)
data1.head()

   FIPStxt State      Area_Name            Attribute        Value
0        0    US  United States      CENSUS_2020_POP  331449281.0
1        0    US  United States  ESTIMATES_BASE_2020  331464948.0
2        0    US  United States    POP_ESTIMATE_2020  331526933.0
3        0    US  United States    POP_ESTIMATE_2021  332048977.0
4        0    US  United States    POP_ESTIMATE_2022  333271411.0

In [22]:
# To make the data easier to work with, we pivot the data to a wide format.
# This will turn the 'Attribute' column's values into their own columns, which is better for analysis and merging.
data1_wide = data1.pivot(index=['FIPStxt','State','Area_Name'], columns='Attribute', values='Value')

# We inspect the new dataframe to check for missing values (nulls) and incorrect data types.
data1_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (np.int64(0), 'US', 'United States') to (np.int64(72000), 'PR', 'Puerto Rico')
Data columns (total 65 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   BIRTHS_2020                      53 non-null     float64
 1   BIRTHS_2021                      53 non-null     float64
 2   BIRTHS_2022                      53 non-null     float64
 3   BIRTHS_2023                      53 non-null     float64
 4   CENSUS_2020_POP                  54 non-null     float64
 5   DEATHS_2020                      53 non-null     float64
 6   DEATHS_2021                      53 non-null     float64
 7   DEATHS_2022                      53 non-null     float64
 8   DEATHS_2023                      53 non-null     float64
 9   DOMESTIC_MIG_2020                53 non-null     float64
 10  DOMESTIC_MIG_2021                53 non-null     float64
 11  DOMESTIC_MIG_2022                53 non-null     float64
 12  DOMESTIC_MIG_2023                53 non-null     float64
 13  ESTIMATES_BASE_2020              54 non-null     float64
 14  Economic_typology_2015           1 non-null      float64
 15  GQ_ESTIMATES_2020                52 non-null     float64
 16  GQ_ESTIMATES_2021                52 non-null     float64
 17  GQ_ESTIMATES_2022                52 non-null     float64
 18  GQ_ESTIMATES_2023                52 non-null     float64
 19  GQ_ESTIMATES_BASE_2020           52 non-null     float64
 20  INTERNATIONAL_MIG_2020           53 non-null     float64
 21  INTERNATIONAL_MIG_2021           53 non-null     float64
 22  INTERNATIONAL_MIG_2022           53 non-null     float64
 23  INTERNATIONAL_MIG_2023           53 non-null     float64
 24  NATURAL_CHG_2020                 53 non-null     float64
 25  NATURAL_CHG_2021                 53 non-null     float64
 26  NATURAL_CHG_2022                 53 non-null     float64
 27  NATURAL_CHG_2023                 53 non-null     float64
 28  NET_MIG_2020                     53 non-null     float64
 29  NET_MIG_2021                     53 non-null     float64
 30  NET_MIG_2022                     53 non-null     float64
 31  NET_MIG_2023                     53 non-null     float64
 32  N_POP_CHG_2020                   53 non-null     float64
 33  N_POP_CHG_2021                   53 non-null     float64
 34  N_POP_CHG_2022                   53 non-null     float64
 35  N_POP_CHG_2023                   53 non-null     float64
 36  POP_ESTIMATE_2020                54 non-null     float64
 37  POP_ESTIMATE_2021                54 non-null     float64
 38  POP_ESTIMATE_2022                54 non-null     float64
 39  POP_ESTIMATE_2023                54 non-null     float64
 40  RESIDUAL_2020                    53 non-null     float64
 41  RESIDUAL_2021                    53 non-null     float64
 42  RESIDUAL_2022                    53 non-null     float64
 43  RESIDUAL_2023                    53 non-null     float64
 44  R_BIRTH_2021                     53 non-null     float64
 45  R_BIRTH_2022                     53 non-null     float64
 46  R_BIRTH_2023                     53 non-null     float64
 47  R_DEATH_2021                     53 non-null     float64
 48  R_DEATH_2022                     53 non-null     float64
 49  R_DEATH_2023                     53 non-null     float64
 50  R_DOMESTIC_MIG_2021              53 non-null     float64
 51  R_DOMESTIC_MIG_2022              53 non-null     float64
 52  R_DOMESTIC_MIG_2023              53 non-null     float64
 53  R_INTERNATIONAL_MIG_2021         53 non-null     float64
 54  R_INTERNATIONAL_MIG_2022         53 non-null     float64
 55  R_INTERNATIONAL_MIG_2023         53 non-null     float64
 56  R_NATURAL_CHG_2021               53 non-null     float64
 57  R_NATURAL_CHG_2022               53 non-null     float64
 58  R_NATURAL_CHG_2023               53 non-null     float64
 59  R_NET_MIG_2021                   53 non-null     float64
 60  R_NET_MIG_2022                   53 non-null     float64
 61  R_NET_MIG_2023                   53 non-null     float64
 62  Rural_Urban_Continuum_Code_2013  1 non-null      float64
 63  Rural_Urban_Continuum_Code_2023  1 non-null      float64
 64  Urban_Influence_2013             1 non-null      float64
dtypes: float64(65)
memory usage: 35.2+ KB

In [ ]:
# After pivoting, many columns have missing data.
# We drop columns with fewer than 40 non-null values to remove irrelevant or sparse data.
data1_wide.dropna(thresh=40, axis=1, inplace=True)

# Inspect the dataframe again to confirm which columns were retained.
data1_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (np.int64(0), 'US', 'United States') to (np.int64(72000), 'PR', 'Puerto Rico')
Data columns (total 61 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   BIRTHS_2020               53 non-null     float64
 1   BIRTHS_2021               53 non-null     float64
 2   BIRTHS_2022               53 non-null     float64
 3   BIRTHS_2023               53 non-null     float64
 4   CENSUS_2020_POP           54 non-null     float64
 5   DEATHS_2020               53 non-null     float64
 6   DEATHS_2021               53 non-null     float64
 7   DEATHS_2022               53 non-null     float64
 8   DEATHS_2023               53 non-null     float64
 9   DOMESTIC_MIG_2020         53 non-null     float64
 10  DOMESTIC_MIG_2021         53 non-null     float64
 11  DOMESTIC_MIG_2022         53 non-null     float64
 12  DOMESTIC_MIG_2023         53 non-null     float64
 13  ESTIMATES_BASE_2020       54 non-null     float64
 14  GQ_ESTIMATES_2020         52 non-null     float64
 15  GQ_ESTIMATES_2021         52 non-null     float64
 16  GQ_ESTIMATES_2022         52 non-null     float64
 17  GQ_ESTIMATES_2023         52 non-null     float64
 18  GQ_ESTIMATES_BASE_2020    52 non-null     float64
 19  INTERNATIONAL_MIG_2020    53 non-null     float64
 20  INTERNATIONAL_MIG_2021    53 non-null     float64
 21  INTERNATIONAL_MIG_2022    53 non-null     float64
 22  INTERNATIONAL_MIG_2023    53 non-null     float64
 23  NATURAL_CHG_2020          53 non-null     float64
 24  NATURAL_CHG_2021          53 non-null     float64
 25  NATURAL_CHG_2022          53 non-null     float64
 26  NATURAL_CHG_2023          53 non-null     float64
 27  NET_MIG_2020              53 non-null     float64
 28  NET_MIG_2021              53 non-null     float64
 29  NET_MIG_2022              53 non-null     float64
 30  NET_MIG_2023              53 non-null     float64
 31  N_POP_CHG_2020            53 non-null     float64
 32  N_POP_CHG_2021            53 non-null     float64
 33  N_POP_CHG_2022            53 non-null     float64
 34  N_POP_CHG_2023            53 non-null     float64
 35  POP_ESTIMATE_2020         54 non-null     float64
 36  POP_ESTIMATE_2021         54 non-null     float64
 37  POP_ESTIMATE_2022         54 non-null     float64
 38  POP_ESTIMATE_2023         54 non-null     float64
 39  RESIDUAL_2020             53 non-null     float64
 40  RESIDUAL_2021             53 non-null     float64
 41  RESIDUAL_2022             53 non-null     float64
 42  RESIDUAL_2023             53 non-null     float64
 43  R_BIRTH_2021              53 non-null     float64
 44  R_BIRTH_2022              53 non-null     float64
 45  R_BIRTH_2023              53 non-null     float64
 46  R_DEATH_2021              53 non-null     float64
 47  R_DEATH_2022              53 non-null     float64
 48  R_DEATH_2023              53 non-null     float64
 49  R_DOMESTIC_MIG_2021       53 non-null     float64
 50  R_DOMESTIC_MIG_2022       53 non-null     float64
 51  R_DOMESTIC_MIG_2023       53 non-null     float64
 52  R_INTERNATIONAL_MIG_2021  53 non-null     float64
 53  R_INTERNATIONAL_MIG_2022  53 non-null     float64
 54  R_INTERNATIONAL_MIG_2023  53 non-null     float64
 55  R_NATURAL_CHG_2021        53 non-null     float64
 56  R_NATURAL_CHG_2022        53 non-null     float64
 57  R_NATURAL_CHG_2023        53 non-null     float64
 58  R_NET_MIG_2021            53 non-null     float64
 59  R_NET_MIG_2022            53 non-null     float64
 60  R_NET_MIG_2023            53 non-null     float64
dtypes: float64(61)
memory usage: 33.5+ KB

In [ ]:
# Fill remaining missing values with 0, assuming a missing value means a count of zero.
data1_wide.fillna(value=0, inplace=True)

# Convert value columns from float to int, since population counts are whole numbers.
data1_wide = data1_wide.astype(int)

# Display the cleaned dataframe.
data1_wide

,,Attribute,BIRTHS_2020,BIRTHS_2021,BIRTHS_2022,BIRTHS_2023,CENSUS_2020_POP,DEATHS_2020,DEATHS_2021,DEATHS_2022,DEATHS_2023,DOMESTIC_MIG_2020,...,R_DOMESTIC_MIG_2023,R_INTERNATIONAL_MIG_2021,R_INTERNATIONAL_MIG_2022,R_INTERNATIONAL_MIG_2023,R_NATURAL_CHG_2021,R_NATURAL_CHG_2022,R_NATURAL_CHG_2023,R_NET_MIG_2021,R_NET_MIG_2022,R_NET_MIG_2023
FIPStxt,State,Area_Name,,,,,,,,,,,,,,,,,,,,,
0,US,United States,894123,3584459,3679254,3653356,331449281,852024,3438423,3456087,3148861,0,...,0,1,3,3,0,0,1,1,3,3
1000,AL,Alabama,13867,57184,58106,58251,5024279,15165,69135,67208,59813,9615,...,6,0,0,1,-2,-1,0,5,6,7
2000,AK,Alaska,2406,9453,9356,9266,733391,1171,5330,6340,5581,-1663,...,-7,1,3,2,5,4,5,-2,-6,-4
4000,AZ,Arizona,18110,75693,79137,78494,7151502,18025,80276,79807,70792,29980,...,4,1,3,2,0,0,1,12,12,7
5000,AR,Arkansas,8509,34927,36298,35566,3011524,8475,40180,40362,36473,2537,...,5,0,1,1,-1,-1,0,6,7,7
6000,CA,California,103133,412506,423922,414120,39538223,74587,345181,318145,302704,-67932,...,-8,1,3,3,1,2,2,-10,-5,-4
8000,CO,Colorado,15593,62137,62682,62498,5773714,11914,46481,49599,45099,7169,...,1,0,1,2,2,2,3,1,2,3
9000,CT,Connecticut,8465,33942,35572,34957,3605944,11938,34571,34833,32842,-21420,...,-2,1,4,4,0,0,0,7,1,1
10000,DE,Delaware,2579,10174,10883,10725,989948,2959,11228,11488,10897,2195,...,10,0,2,2,-1,0,0,14,14,12
11000,DC,District of Columbia,2187,8508,8399,7627,689545,2004,5837,5572,5020,-15475,...,-2,2,6,10,4,4,3,-7,0,8
11001,DC,District of Columbia,2187,8508,8399,7627,689545,2004,5837,5572,5020,-15475,...,-2,2,6,10,4,4,3,-7,0,8
12000,FL,Florida,50294,207942,222003,223578,21538187,56383,250389,260220,231181,61782,...,8,2,5,8,-2,-1,0,13,19,16
13000,GA,Georgia,29847,121276,125599,125664,10711908,24771,109501,110380,97847,11606,...,5,0,2,2,1,1,2,4,9,8
15000,HI,Hawaii,3836,15528,15746,15167,1455271,2843,12152,13375,12812,-4831,...,-7,1,4,3,2,1,1,-5,-6,-4
16000,ID,Idaho,5467,21850,22418,22456,1839106,3629,17141,18938,16817,8814,...,7,0,0,2,2,1,2,27,15,10
17000,IL,Illinois,33452,131888,129614,127235,12812508,35296,128385,127064,116782,-22545,...,-6,0,2,3,0,0,0,-8,-8,-3
18000,IN,Indiana,19436,77712,80234,79587,6785528,19149,77868,79739,72079,1596,...,0,0,2,2,0,0,1,3,3,3
19000,IA,Iowa,9104,35887,36848,36898,3190369,8036,35499,35708,33119,-1270,...,-1,1,2,2,0,0,1,1,0,1
20000,KS,Kansas,8510,34168,34547,34768,2937880,6984,32824,33274,30329,-1920,...,-1,0,1,1,0,0,1,-1,0,0
21000,KY,Kentucky,12579,51364,52384,52380,4505836,12785,58401,61410,54385,1010,...,2,0,1,1,-1,-2,0,1,3,3
22000,LA,Louisiana,13555,57028,56541,56209,4657757,14807,56872,56876,50094,-5154,...,-6,0,1,2,0,0,1,-5,-8,-4
23000,ME,Maine,2997,11590,12009,11945,1362359,3704,16116,17977,16998,1803,...,6,0,1,1,-3,-4,-3,13,11,8
24000,MD,Maryland,17156,67431,68904,67969,6177224,16929,58995,57559,53770,-5257,...,-5,1,3,5,1,1,2,-1,-3,0
25000,MA,Massachusetts,17113,66441,69069,68387,7029917,22133,61652,63566,61404,-27235,...,-5,2,6,7,0,0,1,-1,-2,1
26000,MI,Michigan,26588,102799,104411,101911,10077331,31057,115214,117927,105941,-4859,...,-1,0,1,2,-1,-1,0,-2,1,0
27000,MN,Minnesota,16461,63012,64630,63754,5706494,12746,51396,53436,49911,-1510,...,0,1,2,2,2,2,2,0,-2,1
28000,MS,Mississippi,8503,35004,34786,34628,2961279,9676,41703,40733,36032,-2122,...,0,0,0,1,-2,-2,0,-1,-1,0
29000,MO,Missouri,17239,68820,68857,68334,6154913,16745,75365,75735,68389,-1291,...,1,0,1,1,-1,-1,0,3,2,3
30000,MT,Montana,2812,10841,11219,11206,1084225,2518,12151,12896,11377,2746,...,8,0,1,0,-1,-1,0,19,15,8
31000,NE,Nebraska,6046,24410,24174,24195,1961504,4462,19570,19473,18496,-778,...,0,0,2,2,2,2,2,-2,0,2
32000,NV,Nevada,8167,33361,33542,33055,3104614,7009,32390,33435,29322,10289,...,2,1,3,1,0,0,1,9,9,4
33000,NH,New Hampshire,2994,12044,12332,12155,1377529,3481,13709,14674,14264,1272,...,3,1,2,0,-1,-1,-1,7,10,3
34000,NJ,New Jersey,24722,98001,102468,102055,9288994,33966,83971,82566,76563,-9361,...,-4,1,4,5,1,2,2,-2,-2,0
35000,NM,New Mexico,5327,21433,21151,20728,2117522,5523,24640,25470,22344,702,...,0,1,2,1,-1,-2,0,0,0,1
36000,NY,New York,53056,205414,210106,207450,20201249,72698,177088,176382,165914,-72398,...,-11,1,3,3,1,1,2,-13,-11,-7
37000,NC,North Carolina,28675,116747,121639,121148,10439388,25861,115480,117926,108491,12492,...,9,0,2,2,0,0,1,10,11,11
38000,ND,North Dakota,2563,10019,9839,9649,779094,1751,7766,7390,6945,-448,...,0,0,1,2,2,3,3,-4,-1,2
39000,OH,Ohio,32340,128271,128796,128826,11799448,33762,146812,149079,131288,-2867,...,0,0,2,2,-1,-1,0,-1,1,2
40000,OK,Oklahoma,11579,47473,48121,48073,3959353,10353,50805,51669,45506,3825,...,5,0,1,2,0,0,0,7,8,7
41000,OR,Oregon,10281,39660,40521,39046,4237256,9546,41943,46369,43285,6407,...,-1,0,1,1,0,-1,-1,3,-2,0
42000,PA,Pennsylvania,32903,130245,131600,129489,13002700,40289,155661,155062,140568,-3696,...,-1,0,2,2,-2,-1,0,2,-1,0
44000,RI,Rhode Island,2546,10030,10386,10006,1097379,3389,11332,11078,10434,-430,...,-2,1,2,5,-1,0,0,1,-2,2
45000,SC,South Carolina,13492,55815,57508,57581,5118425,14065,64911,64636,58852,14724,...,15,0,2,1,-1,-1,0,13,17,17
46000,SD,South Dakota,2832,11063,11324,11369,886667,2020,9779,9226,8556,299,...,5,1,3,2,1,2,3,8,12,7
47000,TN,Tennessee,19250,79463,82053,82244,6910840,18931,89405,91616,81216,14621,...,8,0,1,1,-1,-1,0,7,13,10
48000,TX,Texas,88268,364918,384024,390494,29145505,55732,270419,261745,232241,52914,...,6,1,3,4,3,4,5,8,11,10
49000,UT,Utah,11862,45703,46371,45965,3271616,4964,21993,23370,21169,4636,...,0,0,1,3,7,6,7,9,5,3
50000,VT,Vermont,1303,5153,5385,5072,643077,1565,6447,7216,6876,-66,...,1,0,1,2,-2,-2,-2,8,3,3
51000,VA,Virginia,23580,94275,96018,95669,8631393,19723,83763,86329,79980,-31,...,0,1,4,3,1,1,1,1,1,2
53000,WA,Washington,21105,82602,83874,82523,7705281,15173,64924,70848,67663,11889,...,-2,1,4,3,2,1,1,0,4,1
54000,WV,West Virginia,4296,17056,17100,17263,1793716,5871,27613,30006,25929,-813,...,2,0,1,0,-5,-7,-4,2,1,2
55000,WI,Wisconsin,15554,60034,60702,59839,5893718,14171,61983,63601,58692,13,...,1,0,1,2,0,0,0,-2,2,3
56000,WY,Wyoming,1584,6164,6046,5882,576851,1290,6176,6754,5779,436,...,3,0,0,0,0,-1,0,3,4,4
72000,PR,Puerto Rico,0,0,0,0,3285874,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Data File 2 dataframe
Here we will load the data_file_2 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [25]:
data2 = pd.read_csv(data_file_2)

# Drop duplicate rows to ensure data integrity before any transformations.
data2.drop_duplicates(inplace=True)
data2.head()

,FIPS Code,State,Area name,Attribute,Value
0,0,US,United States,"Less than high school graduate, 2019-23",2.423022e+07
1,0,US,United States,"High school graduate (or equivalency), 2019-23",5.983649e+07
2,0,US,United States,"Some college or associate degree, 2019-23",6.441365e+07
3,0,US,United States,"Bachelor's degree or higher, 2019-23",7.995430e+07
4,0,US,United States,Percent of adults who are not high school grad...,1.060707e+01

In [26]:
# To ensure consistency for merging, we rename columns to match the first dataframe.
data2.rename(columns={'Area name': 'Area_Name', 'FIPS Code': 'FIPStxt'}, inplace=True)
data2.head()

,FIPStxt,State,Area_Name,Attribute,Value
0,0,US,United States,"Less than high school graduate, 2019-23",2.423022e+07
1,0,US,United States,"High school graduate (or equivalency), 2019-23",5.983649e+07
2,0,US,United States,"Some college or associate degree, 2019-23",6.441365e+07
3,0,US,United States,"Bachelor's degree or higher, 2019-23",7.995430e+07
4,0,US,United States,Percent of adults who are not high school grad...,1.060707e+01

In [27]:
# Similar to the first dataframe, we pivot the second dataframe to a wide format.
data2_wide = data2.pivot(index=['FIPStxt','State','Area_Name'], columns='Attribute', values='Value')

# We inspect the new dataframe to check for missing values and data types.
data2_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (np.int64(0), 'US', 'United States') to (np.int64(72000), 'PR', 'Puerto Rico')
Data columns (total 8 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Bachelor's degree or higher, 2019-23                                      54 non-null     float64
 1   High school graduate (or equivalency), 2019-23                            54 non-null     float64
 2   Less than high school graduate, 2019-23                                   54 non-null     float64
 3   Percent of adults completing some college or associate degree, 2019-23    54 non-null     float64
 4   Percent of adults who are high school graduates (or equivalent), 2019-23  54 non-null     float64
 5   Percent of adults who are not high school graduates, 2019-23              54 non-null     float64
 6   Percent of adults with a bachelor's degree or higher, 2019-23             54 non-null     float64
 7   Some college or associate degree, 2019-23                                 54 non-null     float64
dtypes: float64(8)
memory usage: 11.1+ KB

In [ ]:
# Display the pivoted dataframe to visually inspect for any formatting inconsistencies.
data2_wide

,,Attribute,"Bachelor's degree or higher, 2019-23","High school graduate (or equivalency), 2019-23","Less than high school graduate, 2019-23","Percent of adults completing some college or associate degree, 2019-23","Percent of adults who are high school graduates (or equivalent), 2019-23","Percent of adults who are not high school graduates, 2019-23","Percent of adults with a bachelor's degree or higher, 2019-23","Some college or associate degree, 2019-23"
FIPStxt,State,Area_Name,,,,,,,,
0,US,United States,79954302.0,59836489.0,24230217.0,28.197846,26.194137,10.607067,35.000950,64413653.0
1000,AL,Alabama,957081.0,1046374.0,409381.0,30.028286,30.344616,11.871959,27.755139,1035466.0
2000,AK,Alaska,152432.0,141206.0,31854.0,33.287559,28.941408,6.528757,31.242276,162411.0
4000,AZ,Arizona,1627462.0,1171693.0,544528.0,33.000824,23.477843,10.911001,32.610332,1646950.0
5000,AR,Arkansas,513221.0,702778.0,233857.0,29.060040,34.386203,11.442382,25.111375,593923.0
6000,CA,California,9834361.0,5496195.0,4149146.0,27.695487,20.400707,15.400748,36.503058,7461496.0
8000,CO,Colorado,1806355.0,811023.0,292446.0,27.948508,20.082114,7.241390,44.727988,1128710.0
9000,CT,Connecticut,1062403.0,647094.0,219549.0,23.839007,25.548028,8.668051,41.944913,603807.0
10000,DE,Delaware,250626.0,206192.0,61144.0,27.092993,29.023059,8.606473,35.277475,192480.0
11000,DC,District of Columbia,307906.0,70322.0,34651.0,14.765920,14.517161,7.153297,63.563622,71527.0
11001,DC,District of Columbia,307906.0,70322.0,34651.0,14.765920,14.517161,7.153297,63.563622,71527.0
12000,FL,Florida,5263931.0,4346402.0,1643437.0,28.999636,27.421577,10.368492,33.210295,4596529.0
13000,GA,Georgia,2480907.0,1950698.0,801324.0,27.852120,26.894828,11.048082,34.204970,2020131.0
15000,HI,Hawaii,364398.0,273812.0,72950.0,30.777310,26.652235,7.100786,35.469669,316191.0
16000,ID,Idaho,388032.0,322573.0,103570.0,34.568627,25.923658,8.323428,31.184286,430144.0
17000,IL,Illinois,3249494.0,2207546.0,851323.0,27.810428,25.261990,9.742090,37.185492,2430244.0
18000,IN,Indiana,1313086.0,1496214.0,445651.0,28.608599,32.816719,9.774540,28.800141,1304353.0
19000,IA,Iowa,660619.0,649969.0,145119.0,31.991436,30.365629,6.779754,30.863182,684769.0
20000,KS,Kansas,679664.0,495115.0,156595.0,31.134391,25.609931,8.099910,35.155768,601919.0
21000,KY,Kentucky,830856.0,1006715.0,352966.0,28.836086,32.705122,11.466797,26.991996,887620.0
22000,LA,Louisiana,825794.0,1012121.0,407400.0,27.809272,32.541426,13.098609,26.550693,864939.0
23000,ME,Maine,359323.0,310243.0,56031.0,28.627229,30.516806,5.511445,35.344521,291033.0
24000,MD,Maryland,1826045.0,1014175.0,382701.0,24.571447,23.735534,8.956652,42.736366,1049892.0
25000,MA,Massachusetts,2305899.0,1129802.0,425209.0,21.932898,22.844451,8.597671,46.624980,1084720.0
26000,MI,Michigan,2213104.0,1964538.0,564902.0,31.932879,28.195932,8.107727,31.763462,2224908.0
27000,MN,Minnesota,1513374.0,916744.0,239636.0,31.502441,23.520791,6.148312,38.828456,1227836.0
28000,MS,Mississippi,475997.0,589225.0,263266.0,32.574260,29.905375,13.361735,24.158630,641810.0
29000,MO,Missouri,1345230.0,1279442.0,354732.0,29.355020,30.336992,8.411090,31.896898,1238028.0
30000,MT,Montana,266066.0,214759.0,41822.0,32.153284,27.878650,5.429067,34.538999,247688.0
31000,NE,Nebraska,440234.0,324253.0,102256.0,32.823951,25.130904,7.925249,34.119896,423513.0
32000,NV,Nevada,601393.0,602478.0,277389.0,32.549847,27.434234,12.631091,27.384828,714821.0
33000,NH,New Hampshire,401838.0,272558.0,59997.0,27.231769,27.006744,5.944876,39.816611,274829.0
34000,NJ,New Jersey,2771686.0,1662983.0,600736.0,22.043141,25.745880,9.300442,42.910537,1423815.0
35000,NM,New Mexico,438228.0,373330.0,178146.0,31.791545,25.729170,12.277472,30.201813,461295.0
36000,NY,New York,5535503.0,3437438.0,1698537.0,23.754124,24.559904,12.135755,39.550217,3324660.0
37000,NC,North Carolina,2521353.0,1812528.0,744581.0,30.066168,24.959728,10.253380,34.720724,2183348.0
38000,ND,North Dakota,164378.0,130763.0,31418.0,35.861801,25.682659,6.170689,32.284852,182590.0
39000,OH,Ohio,2514129.0,2624935.0,680554.0,28.359331,32.313478,8.377757,30.949434,2303726.0
40000,OK,Oklahoma,733793.0,811387.0,287078.0,30.631104,30.718938,10.868712,27.781246,809067.0
41000,OR,Oregon,1094312.0,676182.0,250221.0,33.111277,22.382647,8.282694,36.223382,1000295.0
42000,PA,Pennsylvania,3157318.0,3039316.0,740736.0,24.207808,33.205152,8.092693,34.494348,2215776.0
44000,RI,Rhode Island,289667.0,205862.0,81676.0,25.666287,26.511355,10.518413,37.303945,199300.0
45000,SC,South Carolina,1136208.0,1019313.0,375697.0,29.890421,28.232892,10.406041,31.470645,1079156.0
46000,SD,South Dakota,185411.0,175713.0,41643.0,32.437175,29.475272,6.985475,31.102079,193370.0
47000,TN,Tennessee,1460501.0,1508292.0,499497.0,27.827153,31.386570,10.394206,30.392071,1337243.0
48000,TX,Texas,6381971.0,4691708.0,2759723.0,28.304397,24.316132,14.303062,33.076409,5461229.0
49000,UT,Utah,739555.0,449786.0,134602.0,33.904769,22.454675,6.719738,36.920818,679141.0
50000,VT,Vermont,197369.0,126179.0,25326.0,24.648593,27.252719,5.470026,42.628662,114122.0
51000,VA,Virginia,2471630.0,1423702.0,516186.0,25.967764,23.891967,8.662416,41.477853,1547397.0
53000,WA,Washington,2097154.0,1176403.0,421541.0,31.687972,21.748401,7.793114,38.770512,1714049.0
54000,WV,West Virginia,295541.0,501118.0,144554.0,25.842143,39.482919,11.389361,23.285576,327989.0
55000,WI,Wisconsin,1333128.0,1207407.0,269431.0,30.951992,29.669059,6.620605,32.758344,1259617.0
56000,WY,Wyoming,118336.0,109885.0,23502.0,36.353867,27.783537,5.942291,29.920304,143781.0
72000,PR,Puerto Rico,702653.0,670172.0,472462.0,23.497594,27.784172,19.587457,29.130778,566777.0

In [ ]:
# Drop columns with fewer than 40 non-null values, consistent with how data1_wide was cleaned.
data2_wide.dropna(thresh=40, axis=1, inplace=True)

# Fill remaining missing values with 0, assuming a missing value means a count of zero.
data2_wide.fillna(value=0, inplace=True)

# Convert value columns from float to int, since education counts are whole numbers.
data2_wide = data2_wide.astype(int)

# Inspect the cleaned dataframe to confirm no remaining nulls.
data2_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (np.int64(0), 'US', 'United States') to (np.int64(72000), 'PR', 'Puerto Rico')
Data columns (total 8 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Bachelor's degree or higher, 2019-23                                      54 non-null     int64
 1   High school graduate (or equivalency), 2019-23                            54 non-null     int64
 2   Less than high school graduate, 2019-23                                   54 non-null     int64
 3   Percent of adults completing some college or associate degree, 2019-23    54 non-null     int64
 4   Percent of adults who are high school graduates (or equivalent), 2019-23  54 non-null     int64
 5   Percent of adults who are not high school graduates, 2019-23              54 non-null     int64
 6   Percent of adults with a bachelor's degree or higher, 2019-23             54 non-null     int64
 7   Some college or associate degree, 2019-23                                 54 non-null     int64
dtypes: int64(8)
memory usage: 11.1+ KB

### Data File 3 dataframe
If you choose not to included a third file for merging, remove or comment out the blocks for data3.

Here we will load the data_file_3 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [30]:
# data3 = pd.read_csv(data_file_3)
# data3.head()

In [31]:
# data3.rename(columns={'FIPS_Code': 'FIPStxt'}, inplace=True)
# data3.head()

In [32]:
# data3_wide = data3.pivot(index=['FIPStxt','State','Area_Name'], columns='Attribute', values='Value')
# data3_wide.info()

In [33]:
# data3_wide.dropna(thresh=40, axis=1, inplace=True)
# data3_wide.info()

In [34]:
# data3_wide.fillna(value=0, inplace=True)
# data3_wide

### Data Merging
Here is the example of a merge of the three sample files. You will need to adjust these blocks for how you wish to merge your selected data files.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you need merge your dataset.</span>
</div>

In [35]:
# Merge the two cleaned dataframes using an inner join on their shared keys.
# FIPStxt, State, and Area_Name are used as the join keys to ensure alignment across both datasets.
# An inner join is used so only rows with matching keys in both dataframes are kept,
# ensuring no incomplete records appear in the final merged dataset.
merged_data_1_2 = pd.merge(data1_wide, data2_wide, on=['FIPStxt', 'State', 'Area_Name'])
merged_data_1_2

,,Attribute,BIRTHS_2020,BIRTHS_2021,BIRTHS_2022,BIRTHS_2023,CENSUS_2020_POP,DEATHS_2020,DEATHS_2021,DEATHS_2022,DEATHS_2023,DOMESTIC_MIG_2020,...,R_NET_MIG_2022,R_NET_MIG_2023,"Bachelor's degree or higher, 2019-23","High school graduate (or equivalency), 2019-23","Less than high school graduate, 2019-23","Percent of adults completing some college or associate degree, 2019-23","Percent of adults who are high school graduates (or equivalent), 2019-23","Percent of adults who are not high school graduates, 2019-23","Percent of adults with a bachelor's degree or higher, 2019-23","Some college or associate degree, 2019-23"
FIPStxt,State,Area_Name,,,,,,,,,,,,,,,,,,,,,
0,US,United States,894123,3584459,3679254,3653356,331449281,852024,3438423,3456087,3148861,0,...,3,3,79954302,59836489,24230217,28,26,10,35,64413653
1000,AL,Alabama,13867,57184,58106,58251,5024279,15165,69135,67208,59813,9615,...,6,7,957081,1046374,409381,30,30,11,27,1035466
2000,AK,Alaska,2406,9453,9356,9266,733391,1171,5330,6340,5581,-1663,...,-6,-4,152432,141206,31854,33,28,6,31,162411
4000,AZ,Arizona,18110,75693,79137,78494,7151502,18025,80276,79807,70792,29980,...,12,7,1627462,1171693,544528,33,23,10,32,1646950
5000,AR,Arkansas,8509,34927,36298,35566,3011524,8475,40180,40362,36473,2537,...,7,7,513221,702778,233857,29,34,11,25,593923
6000,CA,California,103133,412506,423922,414120,39538223,74587,345181,318145,302704,-67932,...,-5,-4,9834361,5496195,4149146,27,20,15,36,7461496
8000,CO,Colorado,15593,62137,62682,62498,5773714,11914,46481,49599,45099,7169,...,2,3,1806355,811023,292446,27,20,7,44,1128710
9000,CT,Connecticut,8465,33942,35572,34957,3605944,11938,34571,34833,32842,-21420,...,1,1,1062403,647094,219549,23,25,8,41,603807
10000,DE,Delaware,2579,10174,10883,10725,989948,2959,11228,11488,10897,2195,...,14,12,250626,206192,61144,27,29,8,35,192480
11000,DC,District of Columbia,2187,8508,8399,7627,689545,2004,5837,5572,5020,-15475,...,0,8,307906,70322,34651,14,14,7,63,71527
11001,DC,District of Columbia,2187,8508,8399,7627,689545,2004,5837,5572,5020,-15475,...,0,8,307906,70322,34651,14,14,7,63,71527
12000,FL,Florida,50294,207942,222003,223578,21538187,56383,250389,260220,231181,61782,...,19,16,5263931,4346402,1643437,28,27,10,33,4596529
13000,GA,Georgia,29847,121276,125599,125664,10711908,24771,109501,110380,97847,11606,...,9,8,2480907,1950698,801324,27,26,11,34,2020131
15000,HI,Hawaii,3836,15528,15746,15167,1455271,2843,12152,13375,12812,-4831,...,-6,-4,364398,273812,72950,30,26,7,35,316191
16000,ID,Idaho,5467,21850,22418,22456,1839106,3629,17141,18938,16817,8814,...,15,10,388032,322573,103570,34,25,8,31,430144
17000,IL,Illinois,33452,131888,129614,127235,12812508,35296,128385,127064,116782,-22545,...,-8,-3,3249494,2207546,851323,27,25,9,37,2430244
18000,IN,Indiana,19436,77712,80234,79587,6785528,19149,77868,79739,72079,1596,...,3,3,1313086,1496214,445651,28,32,9,28,1304353
19000,IA,Iowa,9104,35887,36848,36898,3190369,8036,35499,35708,33119,-1270,...,0,1,660619,649969,145119,31,30,6,30,684769
20000,KS,Kansas,8510,34168,34547,34768,2937880,6984,32824,33274,30329,-1920,...,0,0,679664,495115,156595,31,25,8,35,601919
21000,KY,Kentucky,12579,51364,52384,52380,4505836,12785,58401,61410,54385,1010,...,3,3,830856,1006715,352966,28,32,11,26,887620
22000,LA,Louisiana,13555,57028,56541,56209,4657757,14807,56872,56876,50094,-5154,...,-8,-4,825794,1012121,407400,27,32,13,26,864939
23000,ME,Maine,2997,11590,12009,11945,1362359,3704,16116,17977,16998,1803,...,11,8,359323,310243,56031,28,30,5,35,291033
24000,MD,Maryland,17156,67431,68904,67969,6177224,16929,58995,57559,53770,-5257,...,-3,0,1826045,1014175,382701,24,23,8,42,1049892
25000,MA,Massachusetts,17113,66441,69069,68387,7029917,22133,61652,63566,61404,-27235,...,-2,1,2305899,1129802,425209,21,22,8,46,1084720
26000,MI,Michigan,26588,102799,104411,101911,10077331,31057,115214,117927,105941,-4859,...,1,0,2213104,1964538,564902,31,28,8,31,2224908
27000,MN,Minnesota,16461,63012,64630,63754,5706494,12746,51396,53436,49911,-1510,...,-2,1,1513374,916744,239636,31,23,6,38,1227836
28000,MS,Mississippi,8503,35004,34786,34628,2961279,9676,41703,40733,36032,-2122,...,-1,0,475997,589225,263266,32,29,13,24,641810
29000,MO,Missouri,17239,68820,68857,68334,6154913,16745,75365,75735,68389,-1291,...,2,3,1345230,1279442,354732,29,30,8,31,1238028
30000,MT,Montana,2812,10841,11219,11206,1084225,2518,12151,12896,11377,2746,...,15,8,266066,214759,41822,32,27,5,34,247688
31000,NE,Nebraska,6046,24410,24174,24195,1961504,4462,19570,19473,18496,-778,...,0,2,440234,324253,102256,32,25,7,34,423513
32000,NV,Nevada,8167,33361,33542,33055,3104614,7009,32390,33435,29322,10289,...,9,4,601393,602478,277389,32,27,12,27,714821
33000,NH,New Hampshire,2994,12044,12332,12155,1377529,3481,13709,14674,14264,1272,...,10,3,401838,272558,59997,27,27,5,39,274829
34000,NJ,New Jersey,24722,98001,102468,102055,9288994,33966,83971,82566,76563,-9361,...,-2,0,2771686,1662983,600736,22,25,9,42,1423815
35000,NM,New Mexico,5327,21433,21151,20728,2117522,5523,24640,25470,22344,702,...,0,1,438228,373330,178146,31,25,12,30,461295
36000,NY,New York,53056,205414,210106,207450,20201249,72698,177088,176382,165914,-72398,...,-11,-7,5535503,3437438,1698537,23,24,12,39,3324660
37000,NC,North Carolina,28675,116747,121639,121148,10439388,25861,115480,117926,108491,12492,...,11,11,2521353,1812528,744581,30,24,10,34,2183348
38000,ND,North Dakota,2563,10019,9839,9649,779094,1751,7766,7390,6945,-448,...,-1,2,164378,130763,31418,35,25,6,32,182590
39000,OH,Ohio,32340,128271,128796,128826,11799448,33762,146812,149079,131288,-2867,...,1,2,2514129,2624935,680554,28,32,8,30,2303726
40000,OK,Oklahoma,11579,47473,48121,48073,3959353,10353,50805,51669,45506,3825,...,8,7,733793,811387,287078,30,30,10,27,809067
41000,OR,Oregon,10281,39660,40521,39046,4237256,9546,41943,46369,43285,6407,...,-2,0,1094312,676182,250221,33,22,8,36,1000295
42000,PA,Pennsylvania,32903,130245,131600,129489,13002700,40289,155661,155062,140568,-3696,...,-1,0,3157318,3039316,740736,24,33,8,34,2215776
44000,RI,Rhode Island,2546,10030,10386,10006,1097379,3389,11332,11078,10434,-430,...,-2,2,289667,205862,81676,25,26,10,37,199300
45000,SC,South Carolina,13492,55815,57508,57581,5118425,14065,64911,64636,58852,14724,...,17,17,1136208,1019313,375697,29,28,10,31,1079156
46000,SD,South Dakota,2832,11063,11324,11369,886667,2020,9779,9226,8556,299,...,12,7,185411,175713,41643,32,29,6,31,193370
47000,TN,Tennessee,19250,79463,82053,82244,6910840,18931,89405,91616,81216,14621,...,13,10,1460501,1508292,499497,27,31,10,30,1337243
48000,TX,Texas,88268,364918,384024,390494,29145505,55732,270419,261745,232241,52914,...,11,10,6381971,4691708,2759723,28,24,14,33,5461229
49000,UT,Utah,11862,45703,46371,45965,3271616,4964,21993,23370,21169,4636,...,5,3,739555,449786,134602,33,22,6,36,679141
50000,VT,Vermont,1303,5153,5385,5072,643077,1565,6447,7216,6876,-66,...,3,3,197369,126179,25326,24,27,5,42,114122
51000,VA,Virginia,23580,94275,96018,95669,8631393,19723,83763,86329,79980,-31,...,1,2,2471630,1423702,516186,25,23,8,41,1547397
53000,WA,Washington,21105,82602,83874,82523,7705281,15173,64924,70848,67663,11889,...,4,1,2097154,1176403,421541,31,21,7,38,1714049
54000,WV,West Virginia,4296,17056,17100,17263,1793716,5871,27613,30006,25929,-813,...,1,2,295541,501118,144554,25,39,11,23,327989
55000,WI,Wisconsin,15554,60034,60702,59839,5893718,14171,61983,63601,58692,13,...,2,3,1333128,1207407,269431,30,29,6,32,1259617
56000,WY,Wyoming,1584,6164,6046,5882,576851,1290,6176,6754,5779,436,...,4,4,118336,109885,23502,36,27,5,29,143781
72000,PR,Puerto Rico,0,0,0,0,3285874,0,0,0,0,0,...,0,0,702653,670172,472462,23,27,19,29,566777

In [36]:
# To validate the merge, we inspect the new dataframe.
# This shows us the total number of rows and columns and confirms there are no missing values.
merged_data_1_2.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (np.int64(0), 'US', 'United States') to (np.int64(72000), 'PR', 'Puerto Rico')
Data columns (total 69 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   BIRTHS_2020                                                               54 non-null     int64
 1   BIRTHS_2021                                                               54 non-null     int64
 2   BIRTHS_2022                                                               54 non-null     int64
 3   BIRTHS_2023                                                               54 non-null     int64
 4   CENSUS_2020_POP                                                           54 non-null     int64
 5   DEATHS_2020                                                               54 non-null     int64
 6   DEATHS_2021                                                               54 non-null     int64
 7   DEATHS_2022                                                               54 non-null     int64
 8   DEATHS_2023                                                               54 non-null     int64
 9   DOMESTIC_MIG_2020                                                         54 non-null     int64
 10  DOMESTIC_MIG_2021                                                         54 non-null     int64
 11  DOMESTIC_MIG_2022                                                         54 non-null     int64
 12  DOMESTIC_MIG_2023                                                         54 non-null     int64
 13  ESTIMATES_BASE_2020                                                       54 non-null     int64
 14  GQ_ESTIMATES_2020                                                         54 non-null     int64
 15  GQ_ESTIMATES_2021                                                         54 non-null     int64
 16  GQ_ESTIMATES_2022                                                         54 non-null     int64
 17  GQ_ESTIMATES_2023                                                         54 non-null     int64
 18  GQ_ESTIMATES_BASE_2020                                                    54 non-null     int64
 19  INTERNATIONAL_MIG_2020                                                    54 non-null     int64
 20  INTERNATIONAL_MIG_2021                                                    54 non-null     int64
 21  INTERNATIONAL_MIG_2022                                                    54 non-null     int64
 22  INTERNATIONAL_MIG_2023                                                    54 non-null     int64
 23  NATURAL_CHG_2020                                                          54 non-null     int64
 24  NATURAL_CHG_2021                                                          54 non-null     int64
 25  NATURAL_CHG_2022                                                          54 non-null     int64
 26  NATURAL_CHG_2023                                                          54 non-null     int64
 27  NET_MIG_2020                                                              54 non-null     int64
 28  NET_MIG_2021                                                              54 non-null     int64
 29  NET_MIG_2022                                                              54 non-null     int64
 30  NET_MIG_2023                                                              54 non-null     int64
 31  N_POP_CHG_2020                                                            54 non-null     int64
 32  N_POP_CHG_2021                                                            54 non-null     int64
 33  N_POP_CHG_2022                                                            54 non-null     int64
 34  N_POP_CHG_2023                                                            54 non-null     int64
 35  POP_ESTIMATE_2020                                                         54 non-null     int64
 36  POP_ESTIMATE_2021                                                         54 non-null     int64
 37  POP_ESTIMATE_2022                                                         54 non-null     int64
 38  POP_ESTIMATE_2023                                                         54 non-null     int64
 39  RESIDUAL_2020                                                             54 non-null     int64
 40  RESIDUAL_2021                                                             54 non-null     int64
 41  RESIDUAL_2022                                                             54 non-null     int64
 42  RESIDUAL_2023                                                             54 non-null     int64
 43  R_BIRTH_2021                                                              54 non-null     int64
 44  R_BIRTH_2022                                                              54 non-null     int64
 45  R_BIRTH_2023                                                              54 non-null     int64
 46  R_DEATH_2021                                                              54 non-null     int64
 47  R_DEATH_2022                                                              54 non-null     int64
 48  R_DEATH_2023                                                              54 non-null     int64
 49  R_DOMESTIC_MIG_2021                                                       54 non-null     int64
 50  R_DOMESTIC_MIG_2022                                                       54 non-null     int64
 51  R_DOMESTIC_MIG_2023                                                       54 non-null     int64
 52  R_INTERNATIONAL_MIG_2021                                                  54 non-null     int64
 53  R_INTERNATIONAL_MIG_2022                                                  54 non-null     int64
 54  R_INTERNATIONAL_MIG_2023                                                  54 non-null     int64
 55  R_NATURAL_CHG_2021                                                        54 non-null     int64
 56  R_NATURAL_CHG_2022                                                        54 non-null     int64
 57  R_NATURAL_CHG_2023                                                        54 non-null     int64
 58  R_NET_MIG_2021                                                            54 non-null     int64
 59  R_NET_MIG_2022                                                            54 non-null     int64
 60  R_NET_MIG_2023                                                            54 non-null     int64
 61  Bachelor's degree or higher, 2019-23                                      54 non-null     int64
 62  High school graduate (or equivalency), 2019-23                            54 non-null     int64
 63  Less than high school graduate, 2019-23                                   54 non-null     int64
 64  Percent of adults completing some college or associate degree, 2019-23    54 non-null     int64
 65  Percent of adults who are high school graduates (or equivalent), 2019-23  54 non-null     int64
 66  Percent of adults who are not high school graduates, 2019-23              54 non-null     int64
 67  Percent of adults with a bachelor's degree or higher, 2019-23             54 non-null     int64
 68  Some college or associate degree, 2019-23                                 54 non-null     int64
dtypes: int64(69)
memory usage: 36.8+ KB

In [37]:
# final_merged_data = pd.merge(data3_wide, merged_data_1_2, on=['FIPStxt', 'State', 'Area_Name'])
# final_merged_data

### Data Output

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you want to output your merged dataset.</span>
</div>

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>Data Output:</i></b> replace the output path <b><mark>'data/sample_use_only/sample_output/sample_merged_data.csv'</mark></b> with your path <b><mark>'data/{your_merged_data.csv}'</mark></b>.</span>
</div>

In [39]:
# Save the final merged dataframe to a CSV file for submission.
merged_data_1_2.to_csv('data/output/merged_data.csv')